services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345678Aa
      MYSQL_DATABASE: vegaburguer
      MYSQL_USER: federico
      MYSQL_PASSWORD: federico
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3306:3306"